name: ainidiu
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter
  
  connectivity: ^0.4.8+1
  email_validator: '^1.0.0'
  cupertino_icons: ^0.1.2
  firebase_core: ^0.5.0
  cloud_firestore: ^0.14.0+2
  firebase_auth: ^0.18.0+1
  firebase_storage: ^4.0.0
  google_sign_in: ^4.1.1
  string_similarity: ^1.1.0
  path_provider: ^1.6.16
  flutter_local_notifications: ^1.4.4+4
  firebase_messaging: ^7.0.0
  cloud_functions: ^0.6.0
  shared_preferences: ^0.5.10
  sqflite: ^1.3.1+1
  android_alarm_manager: ^0.4.5+14
  background_fetch: ^0.6.0
  #firebase_cloud_messaging: ^4.0.4+1
  intl: ^0.16.0
  flutter_launcher_icons: ^0.8.1
  
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"

  

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/icon/icon.png